baseURL: "https://www.wenjianhao.com/"
title: Wenjian Hao
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Papers
      url: papers/
      weight: 1
    - name: Projects
      url: projects/
      weight: 2
    - name: Blog
      url: blog/
      weight: 3
    - name: Miscellaneous
      url: miscellaneous/
      weight: 4

params:
  description: "Personal website of Wenjian Hao: quantitative research, machine learning, and data science."
  author: Wenjian Hao
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: true
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["papers", "projects", "blog", "miscellaneous"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: false
  profileMode:
    enabled: true
    title: Wenjian Hao
    subtitle: "I am a Ph.D. candidate in the School of Aeronautics and Astronautics at Purdue University, advised by Dr. Shaoshuai Mou. My research focuses on learning and control of complex dynamical systems, particularly data-driven dynamics learning using linear operators, data-efficient reinforcement learning, sampling-based optimal control, safety-critical control, and robotics. My work aims to develop computationally efficient and reliable learning-based control algorithms for autonomous robotic systems by integrating machine learning with control theory. These methods have been applied to a variety of robotic platforms, including manipulators, quadrupeds, drones, and autonomous ground and surface vehicles."
    imageUrl: "wenjian-hao.jpg"
    imageWidth: 180
    imageHeight: 180
    buttons:
      - name: Papers
        url: papers/
      - name: Projects
        url: projects/
      - name: Blog
        url: blog/
      - name: Miscellaneous
        url: miscellaneous/

  socialIcons:
    - name: Email
      url: "mailto:haowjz@gmail.com"
    - name: Google Scholar
      url: https://scholar.google.com/citations?user=SQ2BSVsAAAAJ&hl=en
    - name: GitHub
      url: https://github.com/wenjianhao

  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: "Wenjian Hao"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
